# Generated by Django 2.2.2 on 2019-06-07 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonces',
            name='categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='annonce.Categorie'),
            preserve_default=False,
        ),
    ]
