# Generated by Django 2.2.2 on 2019-06-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0002_annonces_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonces',
            name='prix',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
