# Generated by Django 2.2.2 on 2019-06-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0003_annonces_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonces',
            name='image',
            field=models.FileField(default=1, upload_to='imgs/'),
            preserve_default=False,
        ),
    ]
